name: sampleCD

on:
  push:
    branches: [ "master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: echo a message
        run: echo 'deploy!'
